### ISSUE TITLE
Device keeps entering DFU when pressing button

### ISSUE THREAD

**Issue by tehmaze** [makerdiary/nrf52-u2f#10]
Flashed with the open_bootloader and app from 0b7d8adc6629dd3ea769ff6010fa24f6fd412fdb

The device is correctly identified:

```
nRF52 U2F Security Key:

  Product ID:	0x520f
  Vendor ID:	0x1915  (Nordic Semiconductor ASA)
  Version:	1.00
  Serial Number:	000000000000
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Nordic Semiconductor
  Location ID:	0x14200000 / 21
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0
```

But when I press the button, the red LED starts to pulse and it boots into Open DFU:

```
Open DFU Bootloader:

  Product ID:	0x521f
  Vendor ID:	0x1915  (Nordic Semiconductor ASA)
  Version:	1.00
  Serial Number:	E913D22507A8
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Nordic Semiconductor
  Location ID:	0x14200000 / 22
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0
```

Please advise.

**Comment by caizelin** [comment]
@tehmaze Pls check if you have undefined the marco `CONFIG_GPIO_AS_PINRESET` in your application's makefile. The pin `P0.18` connected to the button should be configed as `GPIO`.
You can erase the `pselreset` by flashing this example: https://github.com/makerdiary/nrf52840-mdk-usb-dongle/tree/master/examples/nrf5-sdk/pselreset_erase

**Comment by tehmaze** [comment]
Thanks this worked, the U2F key is now usable as expected. Perhaps put this recommendation in the installation guide?

**Comment by hschraep** [comment]
Hello is this fix in the downloadable prebuild firmware hex file. I think not because the problem is still there. Or did i need to flash this pselreset_erase hex file over the prebuid FW?

**Comment by caizelin** [comment]
> Hello is this fix in the downloadable prebuild firmware hex file. I think not because the problem is still there. Or did i need to flash this pselreset_erase hex file over the prebuid FW?

@hschraep in your case, you should flash the pselreset_erase hex file first to recover the `pselreset`.

**Comment by hschraep** [comment]
@caizelin , thanks this helps. problem solved
