### ISSUE TITLE
./generate-certs.sh issue

### ISSUE THREAD

**Issue by adrianpisabarrogarcia** [makerdiary/nrf52-u2f#20]
Hi when I run ./generate-certs.sh in my terminal gives me this problem:

Can't open myserver.cnf for reading, No such file or directory
140408292447552:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('myserver.cnf','r')
140408292447552:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:

I'm doing the steps with Ubuntu 20.04.1 LTS
![Captura de pantalla de 2020-08-15 04-34-37](https://user-images.githubusercontent.com/32883172/90303719-a873e780-deb0-11ea-8c63-3ebdbdb96e0d.png)

**Comment by Clem-** [comment]
Did you check that the file `myserver.cnf` exists in `nrf52-u2f\certs`?
